steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    id: Install dependencies with npm
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    env:
      - "REACT_APP_CODEBASE_VERSION=$TAG_NAME"
    id: Create an optimized production build with npm
  - name: "gcr.io/$PROJECT_ID/firebase"
    args:
      [
        "deploy",
        "-P",
        "PROD",
        "-m",
        "Deploy from google cloud build trigger to PROD",
      ]
    id: Deploy to Firebase with firebase
