//ABComparison actions --------------------------

export const SET_FETCHING_AB_COMPARISON_DATA =
	"SET_FETCHING_AB_COMPARISON_DATA";
export const SET_ERROR_FETCHING_AB_COMPARISON_DATA =
	"SET_ERROR_FETCHING_AB_COMPARISON_DATA";
export const SET_GLOBAL_CUMULATIVE_VS_TODAY_COMPARISON_DATA =
	"GLOBAL_CUMULATIVE_VS_TODAY_COMPARISON";
export const SET_COUNTRY_CUMULATIVE_VS_TODAY_COMPARISON_DATA =
	"SET_COUNTRY_CUMULATIVE_VS_TODAY_COMPARISON_DATA";
export const SET_GLOBAL_VS_COUNTRY_CUMULATIVE_COMPARISON_DATA =
	"SET_GLOBAL_VS_COUNTRY_CUMULATIVE_COMPARISON_DATA";
export const SET_GLOBAL_VS_COUNTRY_TODAY_COMPARISON_DATA =
	"SET_GLOBAL_VS_COUNTRY_TODAY_COMPARISON_DATA";

//LastXDays actions --------------------------

export const SET_FETCHING_LAST_X_DAYS_DATA = "SET_FETCHING_LAST_X_DAYS_DATA";
export const SET_ERROR_FETCHING_LAST_X_DAYS_DATA =
	"SET_ERROR_FETCHING_LAST_X_DAYS_DATA";
export const SET_LAST_X_DAYS_DATA = "SET_LAST_X_DAYS_DATA";
