export const GLOBAL_CUMMULATIVE_VS_TODAY_COMPARISON = 1;
export const COUNTRY_CUMMULATIVE_VS_TODAY_COMPARISON = 2;
export const GLOBAL_VS_COUNTRY_CUMMULATIVE_COMPARISON = 3;
export const GLOBAL_VS_COUNTRY_TODAY_COMPARISON = 4;
