export const GLOBAL_CUMULATIVE_VS_TODAY_COMPARISON = 1;
export const COUNTRY_CUMULATIVE_VS_TODAY_COMPARISON = 2;
export const GLOBAL_VS_COUNTRY_CUMULATIVE_COMPARISON = 3;
export const GLOBAL_VS_COUNTRY_TODAY_COMPARISON = 4;
